# Usando a imagem PHP oficial
FROM php:7.4-apache

# Atualizando o sistema e instalando dependências
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Copiando os arquivos do projeto para dentro do contêiner
COPY . /var/www/html

# Expondo a porta 80 para acessar o servidor web
EXPOSE 80

# Comando para iniciar o Apache
CMD ["apache2-foreground"]
